services:
  db:
    image: mongo:latest
    container_name: todos_db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: todos_db_data
        target: /data/db
  # api:
  #   image: dpills/fastapi-todos:1.0.0
  #   container_name: fastapi-todos
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

volumes:
  todos_db_data: