services:
  db:
    image: mongo:latest
    container_name: todos_db
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: todos_db_data
        target: /data/db

volumes:
  todos_db_data: